version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - test_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
