name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build and test Spring Boot Backend
        run: |
          cd backend
          ./mvnw clean install
          ./mvnw test

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and build React Frontend
        run: |
          cd frontend
          npm install
          npm run build

#      - name: Run frontend tests
#        run: |
#          cd frontend
#          npm test

  deploy:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Backend
        run: |
          cd backend
          # F端gen Sie hier Ihre Bereitstellungsbefehle f端r das Backend ein
          echo "Deploying the backend application..."

      - name: Deploy Frontend
        run: |
          cd frontend
          # F端gen Sie hier Ihre Bereitstellungsbefehle f端r das Frontend ein
          echo "Deploying the frontend application..."
