name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'


      - name: Build and test Spring Boot Backend
        run: |
          cd backend
          export JAVA_HOME=${{ steps.setup-java.outputs.path }}
          ./mvnw clean install
          ./mvnw test

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies and build React Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Run frontend tests
        run: |
          cd frontend
          npm test
        env:
          CI: true
  deploy:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Backend
        run: |
          cd backend
            ./mvnw clean install
            ./mvnw spring-boot:run

      - name: Deploy Frontend
        run: |
          cd frontend
            npm start